version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: ./AspNetCoreBook
    ports:
      - "5048:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=bookdb;Username=postgres;Password=12345678;
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
