using AspNetCoreBook.Models;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.EntityFrameworkCore;

namespace AspNetCoreBook.Data;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    public DbSet<Book> Books { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Title).IsRequired().HasMaxLength(200);
            entity.Property(e => e.Author).IsRequired().HasMaxLength(100);
            entity.Property(e => e.PublishedYear).IsRequired();
        });
    }
}

/*
CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Author" character varying(100) NOT NULL,
    "PublishedYear" integer NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY("Id")
);
*/
